/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"
#include <stdio.h>

void *
inicializa_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	unsigned int semilla = (unsigned int)*argp;
        printf("\n <-Recibo < Semilla: %d, Argp=%ld:-",semilla,*argp);
        srandom(semilla);

	return (void *) &result;
}

double *
obtiene_siguiente_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static double result;

	long temp;
        temp=random();
        result=(double)temp;
        printf("\n   >---->Envio random(cast): %f-", result);
	return &result;
}
