/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

char *host;

CLIENT * Conectar_servidor(){
CLIENT * clnt;
clnt = clnt_create(host, RAND_PROG, RAND_VERS, "udp");
if (clnt == NULL){
clnt_pcreateerror (host);
exit(1);
}
return clnt;
}

void inicializa_random(long miSemilla){
void * result_1;
CLIENT * clnt;
clnt=Conectar_servidor();
result_1 = inicializa_random_1(&miSemilla, clnt);
if(result_1 == (void*) NULL){
clnt_perror(clnt, "call failed");
}
clnt_destroy(clnt);
}

double obtiene_siguiente_random(void){
double *result_2;
char *obtiene_siguiente_random_1_arg;
CLIENT *clnt;
clnt=Conectar_servidor();
result_2=obtiene_siguiente_random_1((void*)&obtiene_siguiente_random_1_arg, clnt);
if(result_2 == (double*) NULL){
clnt_perror(clnt, "call failed");
}
clnt_destroy(clnt);
return *result_2;
}

void rand_prog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	long  inicializa_random_1_arg;
	double  *result_2;
	char *obtiene_siguiente_random_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RAND_PROG, RAND_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = inicializa_random_1(&inicializa_random_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = obtiene_siguiente_random_1((void*)&obtiene_siguiente_random_1_arg, clnt);
	if (result_2 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
        long misemilla;
        int itera, i;
        
	if (argc != 4) {
		printf ("Error, el uso correcto es: %s  [host] [semilla] [iteraciones]\n", argv[0]);
		exit (1);
	}
	host = argv[1];
        misemilla=(long)atoi(argv[2]);
        itera=atoi(argv[3]);
        inicializa_random(misemilla);
        for(i=0; i<itera; i++)
        printf("%d : %f\n", i, obtiene_siguiente_random());
exit (0);
}
